FROM php:8.1-fpm

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

COPY conf.d/* $PHP_INI_DIR/conf.d/

RUN docker-php-ext-install mysqli pdo pdo_mysql