#!/usr/bin/env php
<?php
const __CORE__ = __DIR__ . '/';
require_once __DIR__ . '/vendor/autoload.php';

use Commands\DB;
use System\App;
use System\DotEnv;
use System\Migrations;

(new DotEnv(__DIR__ . '/.env'))->load();

Migrations::setDb(App::chooseDatabaseConnection(getenv('DB_CONNECTION')));
(new DB())->run();
